version: '3.4'

services:
  modelbindingsample:
    image: ${DOCKER_REGISTRY-}modelbindingsample
    build:
      context: .
      dockerfile: Dockerfile

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: